apiVersion: v1
kind: Service

metadata:
  name: database
  labels:
    app: rental-database

spec:
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        app: rental-database

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rental-database
  labels:
    app: rental-database

spec:
    replicas: 1
    selector:
        matchLabels:
          app: rental-database
    template:
        metadata:
          labels:
              app: rental-database
        spec:
          containers:
              - name: rental-database
                image: postgres:15.4-alpine
                ports:
                    - containerPort: 5432
                envFrom:
                  - configMapRef:
                      name: rental-env