apiVersion: v1
kind: Service

metadata:
  name: redis
  labels:
    app: rental-redis

spec:
    ports:
        - port: 6379
          targetPort: 6379
    selector:
        app: rental-redis

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rental-redis
  labels:
    app: rental-redis

spec:
    replicas: 1
    selector:
        matchLabels:
          app: rental-redis
    template:
        metadata:
          labels:
              app: rental-redis
        spec:
          containers:
              - name: rental-redis
                image: redis:7-alpine
                ports:
                    - containerPort: 6379
                envFrom:
                  - configMapRef:
                      name: rental-env