"""some constraints are added

Revision ID: a61fc737f8d7
Revises: 79c8982df490
Create Date: 2024-08-28 15:40:23.201347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61fc737f8d7'
down_revision: Union[str, None] = '79c8982df490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contracts', 'home_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contracts', 'renter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contracts', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('listing_images', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'balance_due')
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('receipts', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('receipts', 'renter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('receipts', 'balance_due')
    op.drop_column('receipts', 'total_paid')
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'reviewee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.alter_column('reviews', 'reviewee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('receipts', sa.Column('total_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('receipts', sa.Column('balance_due', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.alter_column('receipts', 'renter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('receipts', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('payments', sa.Column('balance_due', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.alter_column('notifications', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listing_images', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contracts', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contracts', 'renter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contracts', 'home_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
